repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check (via Guix)
        entry: .githooks/ruff-check
        language: system
        types: [python]
        args: [--fix]
        require_serial: true
      
      - id: ruff-format
        name: ruff format (via Guix)
        entry: .githooks/ruff-format
        language: system
        types: [python]
        require_serial: true

      - id: pyright
        name: pyright (via Guix)
        entry: .githooks/pyright
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
        args: [bibmgr/]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]